/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/home'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as RolesIndexImport } from './routes/roles/index'
import { Route as VehiclesStatusImport } from './routes/vehicles/status'
import { Route as VehiclesConfigImport } from './routes/vehicles/config'
import { Route as VehiclesEditIdImport } from './routes/vehicles/edit.$id'
import { Route as UsersEditIdImport } from './routes/users/edit.$id'

// Create/Update Routes

const HomeRoute = HomeImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const RolesIndexRoute = RolesIndexImport.update({
  path: '/roles/',
  getParentRoute: () => rootRoute,
} as any)

const VehiclesStatusRoute = VehiclesStatusImport.update({
  path: '/vehicles/status',
  getParentRoute: () => rootRoute,
} as any)

const VehiclesConfigRoute = VehiclesConfigImport.update({
  path: '/vehicles/config',
  getParentRoute: () => rootRoute,
} as any)

const VehiclesEditIdRoute = VehiclesEditIdImport.update({
  path: '/vehicles/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const UsersEditIdRoute = UsersEditIdImport.update({
  path: '/users/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/vehicles/config': {
      id: '/vehicles/config'
      path: '/vehicles/config'
      fullPath: '/vehicles/config'
      preLoaderRoute: typeof VehiclesConfigImport
      parentRoute: typeof rootRoute
    }
    '/vehicles/status': {
      id: '/vehicles/status'
      path: '/vehicles/status'
      fullPath: '/vehicles/status'
      preLoaderRoute: typeof VehiclesStatusImport
      parentRoute: typeof rootRoute
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/edit/$id': {
      id: '/users/edit/$id'
      path: '/users/edit/$id'
      fullPath: '/users/edit/$id'
      preLoaderRoute: typeof UsersEditIdImport
      parentRoute: typeof rootRoute
    }
    '/vehicles/edit/$id': {
      id: '/vehicles/edit/$id'
      path: '/vehicles/edit/$id'
      fullPath: '/vehicles/edit/$id'
      preLoaderRoute: typeof VehiclesEditIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  HomeRoute,
  VehiclesConfigRoute,
  VehiclesStatusRoute,
  RolesIndexRoute,
  UsersIndexRoute,
  UsersEditIdRoute,
  VehiclesEditIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home",
        "/vehicles/config",
        "/vehicles/status",
        "/roles/",
        "/users/",
        "/users/edit/$id",
        "/vehicles/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/vehicles/config": {
      "filePath": "vehicles/config.tsx"
    },
    "/vehicles/status": {
      "filePath": "vehicles/status.tsx"
    },
    "/roles/": {
      "filePath": "roles/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    },
    "/users/edit/$id": {
      "filePath": "users/edit.$id.tsx"
    },
    "/vehicles/edit/$id": {
      "filePath": "vehicles/edit.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
